# Generated by Django 5.1.4 on 2026-05-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='fee_amount',
        ),
    ]
