# Generated by Django 6.0.3 on 2026-07-13 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0007_appointment_visit_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="owner_name",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="owner_phone",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="pet_name",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="pet_type",
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "pet_type",
                    models.CharField(help_text="e.g. Dog, Cat, Bird", max_length=80),
                ),
                ("owner_name", models.CharField(max_length=120)),
                ("owner_phone", models.CharField(max_length=30)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Medical history / general notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="pet",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="appointments.pet",
            ),
            preserve_default=False,
        ),
    ]
