# Generated by Django 6.0.3 on 2026-07-22 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_remove_appointment_owner_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('XRAY', 'X-Ray'), ('MRI', 'MRI'), ('CT', 'CT'), ('BLOOD', 'Blood'), ('OTHER', 'Other')], max_length=10)),
                ('file', models.FileField(upload_to='diagnoses/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=120)),
                ('size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('notes', models.TextField(blank=True, help_text='Sanitised rich-text (HTML) clinical notes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='appointments.pet')),
            ],
            options={
                'verbose_name_plural': 'diagnoses',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapies', models.JSONField(default=list, help_text='List of therapy codes')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('ALTERNATE', 'Alternate days'), ('WEEKLY', 'Weekly'), ('CUSTOM', 'Custom')], max_length=10)),
                ('frequency_custom', models.CharField(blank=True, max_length=120)),
                ('duration', models.CharField(choices=[('4WK', '4 weeks'), ('8WK', '8 weeks'), ('CUSTOM', 'Custom')], max_length=10)),
                ('duration_custom', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='appointments.pet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_no', models.PositiveIntegerField()),
                ('notes', models.TextField(help_text='Sanitised rich-text (HTML) session note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='appointments.treatmentplan')),
            ],
            options={
                'ordering': ['session_no', 'created_at', 'id'],
            },
        ),
    ]
