# Generated by Django 6.0.3 on 2026-07-23 01:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_diagnosis_treatmentplan_progressnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.PositiveIntegerField(help_text='Server-assigned, gapless per-doctor sequence (not client-settable).')),
                ('line_items', models.JSONField(default=list, help_text='List of {description, quantity, unit_price, amount}.')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('payment_mode', models.CharField(choices=[('advance', 'Advance'), ('post_treatment', 'Post-treatment'), ('package', 'Package'), ('partial', 'Partial')], default='post_treatment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='appointments.pet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'unique_together': {('doctor', 'invoice_no')},
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField()),
                ('used_sessions', models.PositiveIntegerField(default=0)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='appointments.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gateway_ref', models.CharField(blank=True, help_text='Gateway payment id; NULL for manual payments.', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appointments.invoice')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='appointments.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='appointments.payment')),
            ],
            options={
                'ordering': ['-processed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PackageSessionConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_consumptions', to='appointments.appointment')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='appointments.package')),
            ],
            options={
                'unique_together': {('package', 'appointment')},
            },
        ),
    ]
