# Generated by Django 6.0.3 on 2026-07-23 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_billing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_phone', models.CharField(max_length=30, unique=True)),
                ('sms_opt_out', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(default='web', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('APPOINTMENT_CREATED', 'Appointment created'), ('APPOINTMENT_ACCEPTED', 'Appointment accepted'), ('APPOINTMENT_RESCHEDULED', 'Appointment rescheduled'), ('APPOINTMENT_CANCELLED', 'Appointment cancelled'), ('INVOICE_GENERATED', 'Invoice generated'), ('PAYMENT_RECEIVED', 'Payment received'), ('DIAGNOSIS_UPLOADED', 'Diagnosis uploaded'), ('TREATMENT_ADDED', 'Treatment plan added'), ('REMINDER', 'Appointment reminder')], max_length=32)),
                ('message', models.TextField(help_text='Human-readable text naming the pet/owner/subject.')),
                ('is_read', models.BooleanField(default=False)),
                ('dedup_key', models.CharField(blank=True, help_text='Idempotency key for catalogue events + reminders; NULL always creates.', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The doctor who receives this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('FCM', 'FCM push'), ('INAPP', 'In-app')], max_length=10)),
                ('recipient', models.CharField(help_text='Owner phone (SMS) or device token / doctor id (FCM).', max_length=512)),
                ('notif_type', models.CharField(help_text='Mirrors Notification.type for audit even if the row is gone.', max_length=32)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('MOCK', 'Mock'), ('SKIPPED_OPTED_OUT', 'Skipped (opted out)')], max_length=20)),
                ('detail', models.TextField(blank=True, help_text='Provider ref or error / skip reason.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='appointments.notification')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notif_user_read_created_idx'),
        ),
    ]
