# Generated by Django 6.0.3 on 2026-07-23 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Updated on each appended message; drives inbox ordering.', null=True)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='query', to='appointments.pet')),
            ],
            options={
                'verbose_name_plural': 'queries',
                'ordering': ['-last_message_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QueryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('DOCTOR', 'Doctor'), ('OWNER', 'Owner')], help_text='Set server-side; never client-supplied.', max_length=10)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='appointments.query')),
                ('sender', models.ForeignKey(blank=True, help_text='NULL reserved for owner-seeded messages until an Owner user exists.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QueryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='queries/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=120)),
                ('size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='appointments.querymessage')),
            ],
        ),
    ]
