# Generated by Django 6.0.3 on 2026-07-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.CharField(blank=True, help_text="e.g. '4 years' / '6 months'", max_length=40),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pet',
            name='complaint',
            field=models.TextField(blank=True, help_text='Presenting complaint (first visit)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='complaint_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='referred_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(blank=True, choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Reschedule Requested', 'Reschedule Requested'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Follow-up', 'Follow-up'), ('Review', 'Review'), ('Emergency', 'Emergency'), ('Clinic', 'Clinic'), ('Home', 'Home visit')], default='Follow-up', max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True, help_text='General notes'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(blank=True, help_text='Legacy free-text species', max_length=80),
        ),
    ]
