# Generated by Django 6.0.3 on 2026-07-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_pet_owner_ownerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='requested_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_reason',
            field=models.TextField(blank=True),
        ),
    ]
