# Generated by Django 6.0.3 on 2026-07-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_appointment_requested_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('APPOINTMENT_CREATED', 'Appointment created'), ('APPOINTMENT_ACCEPTED', 'Appointment accepted'), ('APPOINTMENT_RESCHEDULED', 'Appointment rescheduled'), ('APPOINTMENT_CANCELLED', 'Appointment cancelled'), ('INVOICE_GENERATED', 'Invoice generated'), ('PAYMENT_RECEIVED', 'Payment received'), ('DIAGNOSIS_UPLOADED', 'Diagnosis uploaded'), ('TREATMENT_ADDED', 'Treatment plan added'), ('REMINDER', 'Appointment reminder'), ('MESSAGE_RECEIVED', 'New message')], max_length=32),
        ),
    ]
