// Payments & billing hooks (SRS §3.8). SHARED, read-only for the screen tasks:
// import these hooks/types — do NOT edit this file. All JSON goes through the
// api() wrapper (session cookie + CSRF); the receipt PDF is a plain browser GET.

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../lib/http";
import type {
  Invoice,
  InvoiceDetail,
  LineItem,
  Package,
  Payment,
  PaymentMode,
  RevenueRange,
  RevenueSummary,
} from "../lib/types";

// ----- Reads -----

// Invoice list. With a petId it scopes to one patient (?pet=), else all invoices.
export function useInvoices(petId?: number) {
  const pet = petId !== undefined && Number.isFinite(petId) ? String(petId) : undefined;
  return useQuery<Invoice[]>({
    queryKey: ["invoices", pet ?? ""],
    queryFn: () => api<Invoice[]>("/invoices", { params: { pet } }),
  });
}

export function useInvoice(id: number) {
  return useQuery<InvoiceDetail>({
    queryKey: ["invoice", id],
    queryFn: () => api<InvoiceDetail>(`/invoices/${id}`),
    enabled: Number.isFinite(id),
  });
}

export function usePackage(id: number) {
  return useQuery<Package>({
    queryKey: ["package", id],
    queryFn: () => api<Package>(`/packages/${id}`),
    enabled: Number.isFinite(id),
  });
}

export function useRevenue(range: RevenueRange) {
  return useQuery<RevenueSummary>({
    queryKey: ["revenue", range],
    queryFn: () => api<RevenueSummary>("/revenue", { params: { range } }),
  });
}

// ----- Mutations -----

export interface CreateInvoicePayload {
  pet_id: number;
  line_items: LineItem[];
  tax?: number;
  payment_mode: PaymentMode;
  // package mode only: size of the prepaid session bundle to create.
  total_sessions?: number;
}

// Create an itemised invoice. invoice_no / subtotal / total are computed
// server-side. Invalidates the invoice lists so the new row appears.
export function useCreateInvoice() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (payload: CreateInvoicePayload) =>
      api<InvoiceDetail>("/invoices", { method: "POST", body: payload }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["invoices"] });
      qc.invalidateQueries({ queryKey: ["revenue"] });
    },
  });
}

export interface RecordPaymentPayload {
  amount_paid: number;
  gateway_ref?: string | null; // Razorpay ref, or omit for manual/cash
  status?: "PAID" | "PARTIALLY_PAID" | "FAILED";
}

// Record a payment against an invoice (manual/partial). Advances the invoice
// payment_status server-side; refreshes the detail, lists and revenue.
export function useRecordPayment(id: number) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (payload: RecordPaymentPayload) =>
      api<Payment>(`/invoices/${id}/payments`, { method: "POST", body: payload }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["invoice", id] });
      qc.invalidateQueries({ queryKey: ["invoices"] });
      qc.invalidateQueries({ queryKey: ["revenue"] });
    },
  });
}

// Razorpay order returned by the checkout endpoint. `key_id` is the PUBLIC
// (publishable) test/live key for the web checkout widget — never a secret.
export interface CheckoutOrder {
  order_id: string;
  amount: number; // in the smallest currency unit (paise), per Razorpay
  currency: string; // e.g. "INR"
  key_id: string;
  invoice_no: string;
  name: string; // display name for the checkout modal
}

// Create a Razorpay order for the invoice so the web checkout widget can open.
// Settlement is confirmed asynchronously by the idempotent webhook, which flips
// the invoice status — so on success we invalidate the invoice for a refetch.
export function useCheckoutOrder(id: number) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: () => api<CheckoutOrder>(`/invoices/${id}/razorpay-order`, { method: "POST" }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["invoice", id] });
    },
  });
}

// Browser GET href for the downloadable PDF receipt (opens/downloads directly;
// not fetched through api()). Mirrors the /api/v1 base used by lib/http.ts.
export function receiptUrl(id: number): string {
  return `/api/v1/invoices/${id}/receipt`;
}
