// Notifications & reminders hooks (SRS §3.7 + §7). SHARED spine, read-only for
// the screen tasks: import these hooks/types — do NOT edit this file. Everything
// goes through the api() wrapper (session cookie + CSRF); no new HTTP plumbing.
//
// Query-key convention: every key is prefixed with ["notifications", ...], so
// the mark-read mutations can invalidate the whole family with a single
// ["notifications"] key and BOTH the feed and the unread badge refetch without
// a page reload.

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../lib/http";
import type { NotificationFeed, NotificationPref, UnreadCount } from "../lib/types";

// ----- Reads -----

// Latest-N notification feed for the dashboard dropdown. Returns the items plus
// the unread tally in one response. `limit` is optional (server default N).
export function useNotifications(limit?: number) {
  const lim = limit !== undefined && Number.isFinite(limit) ? String(limit) : undefined;
  return useQuery<NotificationFeed>({
    queryKey: ["notifications", "feed", lim ?? ""],
    queryFn: () => api<NotificationFeed>("/notifications", { params: { limit: lim } }),
  });
}

// Unread badge count only — cheap enough for the always-mounted sidebar badge.
export function useUnreadCount() {
  return useQuery<UnreadCount>({
    queryKey: ["notifications", "unread-count"],
    queryFn: () => api<UnreadCount>("/notifications/unread-count"),
  });
}

// Owner SMS opt-out preference, looked up by owner phone. Disabled until a
// non-empty phone is supplied so the settings form doesn't fire an empty query.
export function useNotificationPref(ownerPhone: string) {
  return useQuery<NotificationPref>({
    queryKey: ["notifications", "pref", ownerPhone],
    queryFn: () =>
      api<NotificationPref>("/notification-prefs", { params: { owner_phone: ownerPhone } }),
    enabled: !!ownerPhone,
  });
}

// ----- Mutations -----

// Mark a single notification read. Invalidates the whole ["notifications"]
// family so the feed row and the badge both refresh in place.
export function useMarkRead() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: number) =>
      api<void>(`/notifications/${id}/read`, { method: "POST" }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["notifications"] }),
  });
}

// Mark every notification read (dropdown "mark all as read"). Same family
// invalidation → badge drops to zero (and disappears) without a reload.
export function useMarkAllRead() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: () => api<void>("/notifications/mark-all-read", { method: "POST" }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["notifications"] }),
  });
}

// Set (upsert) an owner's SMS opt-out preference. Invalidates the family so any
// mounted pref query re-reads the saved value.
export function useSetNotificationPref() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (payload: NotificationPref) =>
      api<NotificationPref>("/notification-prefs", { method: "PUT", body: payload }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["notifications"] }),
  });
}
